### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by naesheim** [praqma-training/gradle-katas#1]
suggestions:

considering the plural form om kata: gradle-katas

for consistency with gitkatas: gradlekatas

@sofusalbertsen @praqma-thi

**Comment by sofusalbertsen** [comment]
:100: :+1:  @naesheim

**Comment by sofusalbertsen** [comment]
@naesheim gradle-katas

**Comment by sofusalbertsen** [comment]
Just renamed it now.
Need to go through all slides and absolute refs and change.
Will you do that at some point @naesheim ?
Then I'll take artifactory

**Comment by naesheim** [comment]
@sofusalbertsen Yep! I'll do it today
