### ISSUE TITLE
setup file is not quiet when run with gradle >5.1

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/gradle-katas#11]
When running the current version of the setup script from a gradle 5.1, you will get the following 
```
:~/git/gradle-katas/task-creation$ ./setup.sh 
[KATA] Setting up the kata
[KATA] ------
[KATA] 
[KATA] Cleaning up old exercise
[KATA] Initializing new exercise

Select type of project to generate:
  1: basic
  2: groovy-application
  3: groovy-library
  4: java-application
  5: java-library
  6: kotlin-application
  7: kotlin-library
  8: scala-library
Enter selection (default: basic) [1..8] 

Select build script DSL:
  1: groovy
  2: kotlin
Enter selection (default: groovy) [1..2] 1

Project name (default: exercise): 
[KATA] Done!
[KATA] 
[KATA] Don't forget to:
[KATA] 'cd exercise/'
```

If you change the `utils.sh` script to ` gradle -q init --type basic --dsl groovy --project-name exercise` 4.10 will not work.

Needs some querying to find out if you have version 4 or 5 of gradle and call accordingly.

**Comment by michaelin** [comment]
Is this still relevant? Latest gradle version is 6.2.1. Do we want to support two major back?

**Comment by sofusalbertsen** [comment]
@michaelin No we would like to support the latest.
And even if that makes some of the other things break, we will cross that bridge when we get there.
