### ISSUE TITLE
Use "was the output as expected?" wisely

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/gradle-katas#2]
This question is troublesome.
If the user has no idea about the thing we are trying to exercise, then it basically translates to:

```
run idonotknowwhatthisis.sh
was the output as expected?
```

So give the question context eg.

```
The script should run neoncats all over your screen.
run idonotknowwhatthisis.sh
was the output as expected?
```
Then you know what it should do, and can self-evaluate the results.

**Comment by praqma-thi** [comment]
We got rid of most of those IIRC
