### ISSUE TITLE
taskZip is not shown in slides nor text

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/gradle-katas#4]
I needed to google the keywords, and got it to work. should be in the readme file.
https://gist.github.com/nikos/4320123

**Comment by sofusalbertsen** [comment]
or in the build.gradle as comments :)

**Comment by sofusalbertsen** [comment]
Same goes for deleteTask

**Comment by naesheim** [comment]
Example of zip task in build.gradle file. Example of delete task in notes
