### ISSUE TITLE
Create a build task assignment unclear.

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/gradle-katas#5]
I am uncertain if people know what to do here:

> Now, write to the file where you define the author of the file.

Should one just paste #define AUTHOR $whoami or is this a format that needs to be explained?

**Comment by naesheim** [comment]
Is it missing _how_ you would write to a file, or _what_ you should write to the file?

**Comment by sofusalbertsen** [comment]
Writing a file have been trained, it's more the "what". It's first when I come to the next assignment I can see 100% what you meant by the text.

So maybe replace $whoami with <systemproperty name> or something... I'm at least confused before looking at your code :)

**Comment by naesheim** [comment]
Fixed. The header file comes with the exercise
